name: env-nn-eval

channels: 
  - pytorch
  
dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  # PyTorch
  - pytorch=0.4.0
  # Keras
  - tensorflow-gpu
  - keras
  - hdf5
  # scikit-learn
  - scikit-learn=0.21
  # web
  - flask
  - werkzeug
  # testing
  - nose
